# Generated by Django 5.0.4 on 2024-04-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo_combustivel', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='uploads/veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('local', models.CharField(max_length=50)),
                ('combustivel_inicial', models.IntegerField()),
                ('combustivel_fim', models.IntegerField(default=0)),
                ('kilometro_inicial', models.IntegerField(default=0)),
                ('kilometro_final', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
