# Generated by Django 5.0.4 on 2024-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.CharField(auto_created=True, max_length=10),
        ),
    ]
