# Generated by Django 5.0.4 on 2024-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
