# Generated by Django 5.0.4 on 2024-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_alter_pedido_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data',
        ),
    ]
