# Generated by Django 5.0.4 on 2024-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confirmacao',
            field=models.BooleanField(default=False),
        ),
    ]
